name: deploy-image

on:
  workflow_dispatch:
  push:
    branches:
      - master

permissions:
  packages: write

jobs:
  deploy-image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - run: echo "IMAGE_NAME=ghcr.io/killwolfvlad/actions-runner-compose:$(echo ${{ github.ref_name }} | tr / -)-$(echo ${{ github.sha }} | cut -c 1-6)" >> "$GITHUB_ENV"

      - uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_NAME }}
